AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - spec/**/*.rb
    - lib/ajax-datatables-rails.rb
    - lib/generators/rails/templates/*.rb

Documentation:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Metrics/BlockLength:
  Max: 30

Metrics/ModuleLength:
  Max: 130

Metrics/ClassLength:
  Max: 130

Naming/AccessorMethodName:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
