dist: trusty
language: ruby
sudo: required
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
gemfile:
  - gemfiles/rails_4.1.15.gemfile
  - gemfiles/rails_4.2.8.gemfile
  - gemfiles/rails_5.0.2.gemfile
  - gemfiles/rails_5.1.0.gemfile
matrix:
  include:
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4.2.8.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_5.0.2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_5.1.0.gemfile
after_success:
  - bundle exec codeclimate-test-reporter
services:
  - postgresql
  - mysql
addons:
  postgresql: '9.6'
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
  - sh -c "if [ '$DB_ADAPTER' = 'mysql2' ]; then mysql -e 'create database ajax_datatables_rails;'; fi"
  - sh -c "if [ '$DB_ADAPTER' = 'postgresql' ]; then psql -c 'create database ajax_datatables_rails;' -U postgres; fi"
env:
  matrix:
    - DB_ADAPTER=postgresql
    - DB_ADAPTER=mysql2
    - DB_ADAPTER=sqlite3
