language: ruby
cache: bundler
sudo: required
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - ruby-head
gemfile:
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.7.gemfile
  - gemfiles/rails_5.2.3.gemfile
  - gemfiles/rails_6.0.1.gemfile
services:
  - postgresql
  - mysql
addons:
  postgresql: '9.6'
before_install:
  - sh -c "if [ '$DB_ADAPTER' = 'mysql2' ]; then mysql -e 'create database ajax_datatables_rails;'; fi"
  - sh -c "if [ '$DB_ADAPTER' = 'postgresql' ]; then psql -c 'create database ajax_datatables_rails;' -U postgres; fi"
  - sh -c "if [ '$DB_ADAPTER' = 'oracle_enhanced' ]; then ./spec/install_oracle.sh; fi"
env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
  matrix:
    - DB_ADAPTER=postgresql
    - DB_ADAPTER=mysql2
    - DB_ADAPTER=sqlite3
    - DB_ADAPTER=oracle_enhanced
matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6.0.1.gemfile
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
