language: ruby
cache: bundler
sudo: required
rvm:
  - 2.6.1
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - ruby-head
gemfile:
  - gemfiles/rails_4.2.11.gemfile
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.2.gemfile
after_success:
  - bundle exec codeclimate-test-reporter
services:
  - postgresql
  - mysql
addons:
  postgresql: '9.6'
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_install:
  - gem update --system
  # - gem install bundler --no-document
  - sh -c "if [ '$DB_ADAPTER' = 'mysql2' ]; then mysql -e 'create database ajax_datatables_rails;'; fi"
  - sh -c "if [ '$DB_ADAPTER' = 'postgresql' ]; then psql -c 'create database ajax_datatables_rails;' -U postgres; fi"
  - sh -c "if [ '$DB_ADAPTER' = 'oracle_enhanced' ]; then ./spec/install_oracle.sh; fi"
env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
  matrix:
    - DB_ADAPTER=postgresql
    - DB_ADAPTER=mysql2
    - DB_ADAPTER=sqlite3
    - DB_ADAPTER=oracle_enhanced
matrix:
  allow_failures:
    - env: DB_ADAPTER=oracle_enhanced
