dist: trusty
language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
gemfile:
  - gemfiles/rails_4.2.8.gemfile
  - gemfiles/rails_5.0.2.gemfile
  - gemfiles/rails_5.1.0.gemfile
after_success:
  - bundle exec codeclimate-test-reporter
services:
  - postgresql
  - mysql
addons:
  postgresql: '9.6'
before_script:
  - mysql -e 'create database ajax_datatables_rails;'
  - psql -c 'create database ajax_datatables_rails;' -U postgres
env:
  matrix:
    - DB_ADAPTER=postgresql
    - DB_ADAPTER=mysql2
    - DB_ADAPTER=sqlite3
